name: arango
description: ArangoDB nosql graph database
# version: 1.0.0
# homepage: https://www.example.com
# author: xuty <xty50337@hotmail.com>

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  dio: ^3.0.9
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
