name: arango
description: Dart driver for ArangoDB the native multi-model database
version: 0.1.0
homepage: https://github.com/xtyxtyx/arango-dart
issue_tracker: https://github.com/xtyxtyx/arango-dart/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.9

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
