name: arango
description: Dart driver for ArangoDB the native multi-model nosql database.
version: 0.1.3
homepage: https://github.com/xtyxtyx/arango-dart
issue_tracker: https://github.com/xtyxtyx/arango-dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.5
